export const sampleRishtaProfiles = [
  {
    id: "PIWF-2024-001",
    formNo: "1001",
    regDate: "2024-03-01",
    appliedBy: "Father",
    name: "Muhammad Usman Arshad",
    fatherName: "Muhammad Arshad Arain",
    cnic: "35202-4918273-1",
    gender: "Male",
    dob: "1996-05-14",
    age: 28,
    address: "House 42, Street 7, Cavalry Ground",
    area: "Cantt",
    city: "Lahore",
    province: "Punjab",
    country: "Pakistan",
    phone1: "0300-8451290",
    phone2: "0321-4192801",
    email: "usman.arshad96@gmail.com",
    ancestralLocation: "Kasur",
    residenceType: "Own",
    height: "5 ft 11 in",
    build: "Athletic",
    complexion: "Fair",
    motherTongue: "Punjabi",
    caste: "Arain",
    maritalStatus: "Single",
    children: 0,
    disability: "None / Alhamdullilah",
    religion: "Islam (Sunni / Hanafi)",
    hijab: "Never",
    lastDegree: "BS Computer Science",
    majorSubjects: "Software Engineering & Cloud",
    institute: "FAST NUCES Lahore",
    islamicEducation: "Quran Nazra & Tajweed",
    islamicInstitute: "Jamia Ashrafia Evening",
    occupation: "Senior Software Engineer",
    monthlyIncome: 320000,
    currency: "PKR",
    incomeSource: "Job",
    dependents: 0,
    fatherEdu: "M.Com (Retired Bank VP)",
    motherEdu: "B.A (Homemaker)",
    brothers: 1,
    sisters: 2,
    socialStatus: "Upper Middle",
    background: "Punjabi",
    otherNationality: "None",
    partnerDetails: "Looking for an educated, religious, family-oriented Sunni Muslim girl (Doctor/Engineer/Master degree preferred), age 22-26, Arain or respectable family background.",
    prefGender: "Female",
    prefMinAge: 22,
    prefMaxAge: 26,
    prefCaste: "Arain",
    prefCity: "Lahore",
    personality: "Calm, polite, regular in prayers, enjoys reading and outdoor sports.",
    status: "Active",
    photoUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80"
  },
  {
    id: "PIWF-2024-002",
    formNo: "1002",
    regDate: "2024-03-05",
    appliedBy: "Mother",
    name: "Dr. Ayesha Fatima",
    fatherName: "Chaudhry Tariq Mehmood",
    cnic: "33100-2918471-2",
    gender: "Female",
    dob: "1998-08-20",
    age: 26,
    address: "House 18, Block B, Peoples Colony No. 1",
    area: "Peoples Colony",
    city: "Faisalabad",
    province: "Punjab",
    country: "Pakistan",
    phone1: "0301-7128943",
    phone2: "0345-7890123",
    email: "ayesha.tariq.doc@gmail.com",
    ancestralLocation: "Gojra",
    residenceType: "Own",
    height: "5 ft 5 in",
    build: "Slim",
    complexion: "Very Fair",
    motherTongue: "Urdu",
    caste: "Jutt",
    maritalStatus: "Single",
    children: 0,
    disability: "None / Alhamdullilah",
    religion: "Islam (Sunni)",
    hijab: "Always",
    lastDegree: "MBBS (FCPS Part 1)",
    majorSubjects: "General Medicine",
    institute: "Punjab Medical College (FMC)",
    islamicEducation: "Quran Fahmi & Tajweed Course",
    islamicInstitute: "Al-Huda International",
    occupation: "Resident Medical Officer",
    monthlyIncome: 140000,
    currency: "PKR",
    incomeSource: "Job",
    dependents: 0,
    fatherEdu: "B.Sc Agri (Textile Business Owner)",
    motherEdu: "M.A Islamiyat",
    brothers: 2,
    sisters: 1,
    socialStatus: "Upper Middle",
    background: "Punjabi",
    otherNationality: "None",
    partnerDetails: "Looking for a well-settled doctor or engineer/businessman (preferably from Jutt or noble family), gentle demeanor and religious values.",
    prefGender: "Male",
    prefMinAge: 27,
    prefMaxAge: 32,
    prefCaste: "Jutt",
    prefCity: "Faisalabad / Lahore",
    personality: "Humble, compassionate, observant of Hijab, family-centric and dedicated to medicine.",
    status: "Active",
    photoUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=300&auto=format&fit=crop&q=80"
  },
  {
    id: "PIWF-2024-003",
    formNo: "1003",
    regDate: "2024-03-10",
    appliedBy: "Self",
    name: "Hamza Shafique Rajput",
    fatherName: "Rana Shafique Ahmad",
    cnic: "34101-7182934-5",
    gender: "Male",
    dob: "1994-11-12",
    age: 30,
    address: "Model Town, Street 14",
    area: "Model Town",
    city: "Gujranwala",
    province: "Punjab",
    country: "Pakistan",
    phone1: "0300-6421098",
    phone2: "",
    email: "hamza.rana.biz@gmail.com",
    ancestralLocation: "Wazirabad",
    residenceType: "Own",
    height: "6 ft 0 in",
    build: "Athletic",
    complexion: "Fair",
    motherTongue: "Punjabi",
    caste: "Rajput",
    maritalStatus: "Single",
    children: 0,
    disability: "None / Alhamdullilah",
    religion: "Islam (Sunni)",
    hijab: "Never",
    lastDegree: "BBA (Honors)",
    majorSubjects: "Marketing & Supply Chain",
    institute: "University of Central Punjab",
    islamicEducation: "Quran Nazra",
    islamicInstitute: "Local Mosque",
    occupation: "Managing Director (Family Ceramic Industry)",
    monthlyIncome: 650000,
    currency: "PKR",
    incomeSource: "Business",
    dependents: 1,
    fatherEdu: "B.A (Industrialist)",
    motherEdu: "Intermediate (Homemaker)",
    brothers: 2,
    sisters: 0,
    socialStatus: "Upper Class",
    background: "Punjabi",
    otherNationality: "None",
    partnerDetails: "Seeking an educated and graceful girl from a respectable Rajput family who values family ties.",
    prefGender: "Female",
    prefMinAge: 22,
    prefMaxAge: 27,
    prefCaste: "Rajput",
    prefCity: "Gujranwala / Lahore / Sialkot",
    personality: "Ambitious, respectful, family-oriented, fond of travelling.",
    status: "Active",
    photoUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&auto=format&fit=crop&q=80"
  },
  {
    id: "PIWF-2024-004",
    formNo: "1004",
    regDate: "2024-03-14",
    appliedBy: "Father",
    name: "Zainab Binte Bilal",
    fatherName: "Bilal Zubair Sheikh",
    cnic: "37405-3819201-4",
    gender: "Female",
    dob: "1999-04-18",
    age: 25,
    address: "House 91, Westridge 1",
    area: "Westridge",
    city: "Rawalpindi",
    province: "Punjab",
    country: "Pakistan",
    phone1: "0333-5129845",
    phone2: "0312-9847120",
    email: "bilal.sheikh.pindi@gmail.com",
    ancestralLocation: "Bhera, Sargodha",
    residenceType: "Own",
    height: "5 ft 4 in",
    build: "Medium",
    complexion: "Fair",
    motherTongue: "Urdu",
    caste: "Sheikh",
    maritalStatus: "Single",
    children: 0,
    disability: "None / Alhamdullilah",
    religion: "Islam (Sunni / Hanafi)",
    hijab: "Usually",
    lastDegree: "M.Sc Clinical Psychology",
    majorSubjects: "Child Psychology",
    institute: "Quaid-e-Azam University Islamabad",
    islamicEducation: "Quran Nazra & Tafseer Course",
    islamicInstitute: "Idara Taleem-ul-Quran",
    occupation: "School Counselor & Psychologist",
    monthlyIncome: 110000,
    currency: "PKR",
    incomeSource: "Job",
    dependents: 0,
    fatherEdu: "M.A Economics (Civil Servant)",
    motherEdu: "M.Sc Botany (Teacher)",
    brothers: 1,
    sisters: 1,
    socialStatus: "Upper Middle",
    background: "Punjabi",
    otherNationality: "None",
    partnerDetails: "Looking for an educated, decent professional (Govt Officer, Engineer, Corporate) settled in Rawalpindi/Islamabad.",
    prefGender: "Male",
    prefMinAge: 27,
    prefMaxAge: 31,
    prefCaste: "Sheikh / Any respectable",
    prefCity: "Rawalpindi / Islamabad",
    personality: "Polite, empathetic, creative, enjoys culinary arts and book reading.",
    status: "Active",
    photoUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80"
  },
  {
    id: "PIWF-2024-005",
    formNo: "1005",
    regDate: "2024-02-18",
    appliedBy: "Self",
    name: "Engr. Salman Farooq Gujjar",
    fatherName: "Chaudhry Farooq Akhtar",
    cnic: "36302-8192031-7",
    gender: "Male",
    dob: "1992-07-09",
    age: 32,
    address: "Gulgasht Colony, Street 8",
    area: "Gulgasht",
    city: "Multan",
    province: "Punjab",
    country: "Pakistan",
    phone1: "0302-7319842",
    phone2: "",
    email: "salman.gujjar.engr@gmail.com",
    ancestralLocation: "Khanewal",
    residenceType: "Own",
    height: "5 ft 10 in",
    build: "Medium",
    complexion: "Wheatish",
    motherTongue: "Saraiki",
    caste: "Gujjar",
    maritalStatus: "Divorced",
    children: 1,
    disability: "None",
    religion: "Islam (Sunni)",
    hijab: "Never",
    lastDegree: "B.Sc Electrical Engineering",
    majorSubjects: "Power Systems",
    institute: "Bahauddin Zakariya University Multan",
    islamicEducation: "Quran Nazra",
    islamicInstitute: "Local Madrassa",
    occupation: "Sub Divisional Officer (SDO MEPCO)",
    monthlyIncome: 185000,
    currency: "PKR",
    incomeSource: "Job",
    dependents: 1,
    fatherEdu: "B.Sc (Landlord)",
    motherEdu: "Matric",
    brothers: 3,
    sisters: 1,
    socialStatus: "Middle",
    background: "Punjabi",
    otherNationality: "None",
    partnerDetails: "Looking for an understanding, sincere partner (Single, Divorced, or Widowed), age 24-30.",
    prefGender: "Female",
    prefMinAge: 24,
    prefMaxAge: 30,
    prefCaste: "Gujjar / Any",
    prefCity: "Multan / South Punjab",
    personality: "Responsible, grounded, honest, patient.",
    status: "Active",
    photoUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=300&auto=format&fit=crop&q=80"
  },
  {
    id: "PIWF-2024-006",
    formNo: "1006",
    regDate: "2024-01-20",
    appliedBy: "Guardian",
    name: "Syeda Maryam Bukhari",
    fatherName: "Late Syed Afzal Bukhari",
    cnic: "38403-1928472-6",
    gender: "Female",
    dob: "1995-12-04",
    age: 29,
    address: "Satellite Town, Block D",
    area: "Satellite Town",
    city: "Sargodha",
    province: "Punjab",
    country: "Pakistan",
    phone1: "0345-8912763",
    phone2: "0300-9128345",
    email: "maryam.bukhari@gmail.com",
    ancestralLocation: "Sial Sharif",
    residenceType: "Own",
    height: "5 ft 3 in",
    build: "Medium",
    complexion: "Fair",
    motherTongue: "Punjabi",
    caste: "Syed",
    maritalStatus: "Single",
    children: 0,
    disability: "None / Alhamdullilah",
    religion: "Islam (Sunni / Barelvi)",
    hijab: "Always",
    lastDegree: "M.Phil English Literature",
    majorSubjects: "Linguistics & Literature",
    institute: "University of Sargodha",
    islamicEducation: "Dars-e-Nizami (Sanad)",
    islamicInstitute: "Jamia Syeda Fatima",
    occupation: "Lecturer at Govt Degree College",
    monthlyIncome: 125000,
    currency: "PKR",
    incomeSource: "Job",
    dependents: 0,
    fatherEdu: "M.A (Ex Govt Principal, Deceased)",
    motherEdu: "B.A",
    brothers: 1,
    sisters: 2,
    socialStatus: "Middle",
    background: "Punjabi",
    otherNationality: "None",
    partnerDetails: "Strictly looking for a respectable Syed family groom (Doctor, Engineer, Officer, or Businessman).",
    prefGender: "Male",
    prefMinAge: 29,
    prefMaxAge: 35,
    prefCaste: "Syed",
    prefCity: "Any in Punjab / Islamabad",
    personality: "Deeply religious, gentle, literary mind, devoted daughter.",
    status: "Active",
    photoUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=300&auto=format&fit=crop&q=80"
  },
  {
    id: "PIWF-2024-007",
    formNo: "1007",
    regDate: "2023-11-15",
    appliedBy: "Self",
    name: "Fahad Mirza Mughal",
    fatherName: "Mirza Ikram Baig",
    cnic: "34201-9872145-3",
    gender: "Male",
    dob: "1990-03-25",
    age: 34,
    address: "Paris Road, Mughal Manzil",
    area: "Paris Road",
    city: "Sialkot",
    province: "Punjab",
    country: "Pakistan",
    phone1: "0300-9642180",
    phone2: "",
    email: "fahad.mughal.sports@gmail.com",
    ancestralLocation: "Daska",
    residenceType: "Own",
    height: "5 ft 9 in",
    build: "Athletic",
    complexion: "Fair",
    motherTongue: "Punjabi",
    caste: "Mughal",
    maritalStatus: "Single",
    children: 0,
    disability: "None",
    religion: "Islam (Sunni)",
    hijab: "Never",
    lastDegree: "M.Sc International Trade",
    majorSubjects: "Export Management",
    institute: "University of Manchester (UK)",
    islamicEducation: "Quran Nazra",
    islamicInstitute: "Local Mosque",
    occupation: "Director Sports Goods Export",
    monthlyIncome: 850000,
    currency: "PKR",
    incomeSource: "Business",
    dependents: 0,
    fatherEdu: "B.A (Business Owner)",
    motherEdu: "F.A",
    brothers: 1,
    sisters: 1,
    socialStatus: "Upper Class",
    background: "Punjabi",
    otherNationality: "UK Resident Permit",
    partnerDetails: "Looking for an educated, well-spoken girl who can relocate or travel internationally.",
    prefGender: "Female",
    prefMinAge: 24,
    prefMaxAge: 29,
    prefCaste: "Mughal / Any",
    prefCity: "Sialkot / Lahore / Islamabad",
    personality: "Confident, cultured, sociable, enjoys sports and global cuisine.",
    status: "Matched",
    photoUrl: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=300&auto=format&fit=crop&q=80"
  },
  {
    id: "PIWF-2024-008",
    formNo: "1008",
    regDate: "2023-12-01",
    appliedBy: "Mother",
    name: "Khadija Bibi",
    fatherName: "Late Malik Noor Muhammad",
    cnic: "35201-1928472-8",
    gender: "Female",
    dob: "1988-06-12",
    age: 36,
    address: "Allama Iqbal Town, Ravi Block",
    area: "Iqbal Town",
    city: "Lahore",
    province: "Punjab",
    country: "Pakistan",
    phone1: "0322-4567891",
    phone2: "",
    email: "khadija.noor88@gmail.com",
    ancestralLocation: "Lahore",
    residenceType: "Family",
    height: "5 ft 4 in",
    build: "Medium",
    complexion: "Wheatish",
    motherTongue: "Urdu",
    caste: "Arain",
    maritalStatus: "Widowed",
    children: 1,
    disability: "None",
    religion: "Islam (Sunni)",
    hijab: "Always",
    lastDegree: "M.A Urdu Literature & B.Ed",
    majorSubjects: "Teaching & Urdu",
    institute: "Punjab University Lahore",
    islamicEducation: "Quran Fahmi",
    islamicInstitute: "Local Islamic Center",
    occupation: "Senior School Teacher",
    monthlyIncome: 85000,
    currency: "PKR",
    incomeSource: "Job",
    dependents: 1,
    fatherEdu: "B.A (Deceased)",
    motherEdu: "Matric",
    brothers: 2,
    sisters: 2,
    socialStatus: "Middle",
    background: "Punjabi",
    otherNationality: "None",
    partnerDetails: "Looking for an honorable, mature, responsible gentleman (Widower, Divorced, or Single with good character) who can provide a loving family environment.",
    prefGender: "Male",
    prefMinAge: 36,
    prefMaxAge: 48,
    prefCaste: "Any noble family",
    prefCity: "Lahore",
    personality: "Kind-hearted, patient, religious, excellent homemaker.",
    status: "Active",
    photoUrl: "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=300&auto=format&fit=crop&q=80"
  }
];
